create table patients (
    Id integer primary key generated by default as identity,
    FullName varchar(255) not null,
    Gender varchar(255) not null,
    Birthdate date not null,
    Address varchar(255) not null,
    InsuranceNum integer not null
);
